# Generated by Django 3.2.3 on 2021-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_user_orderplacrd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('S', 'SAMSUNG'), ('O', 'OPPO'), ('A', 'APPLE'), ('V', 'VIVO'), ('T', 'TOP WERE'), ('B', 'BOTTOM WERE')], max_length=20),
        ),
    ]
