# Generated by Django 3.1.7 on 2021-11-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211130_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('S', 'SAMSUNG'), ('O', 'OPPO'), ('A', 'APPLE'), ('V', 'VIVO'), ('T', 'TOP WERE'), ('B', 'BOTTOM WERE'), ('D', 'DELL'), ('AS', 'ASUS'), ('H', 'HP'), ('DL', 'DELL'), ('TO', 'TOSHIBA')], max_length=20),
        ),
    ]
